### ISSUE TITLE
Release package

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatpy#11]
Need to release the package: polish it and put it on PyPI.

TODO:

- [x] add documentation
  - [x] get documentation buildable
  - [x] #9 
  - [x] #35
  - [x] #36
- [x] add tests
  - [x] use the example non-trivial calls as tests for data typing #31 
  - [x] #33 
- [x] make sure the endpoint interfaces are the same 
  - [x] rename endpoints to pub_ when needed
  - [x] double check that argument order is the same
  - [x] add support for `geo_value = "*"` default on most endpoints
  - [x] #34
- [x] bug fix
- [x] make sure the API JSON -> Pandas DataFrame type casting is correct and fast #28 
- [x] remove non-Pandas return options and return df by default (for most endpoints) #28
